### ISSUE TITLE
Erratic Behavior

### ISSUE THREAD

**Issue by SapitoSucio** [X-EcutiOnner/SimpleROHook#3]
Hello there, first of all, thank you for maintaining this piece of art, second of all, I have successfully compiled and injected to a 20220330 client but there seems to be a problem, like an offset on the button functions or something.

Activating "Show FPS" shows nothing
Activating "Show Object Information" **shows** FPS
3D Map Grip not working at all

On Extras, activating the 44khz fix shows a ton of info on screen, that I believe is not related to the 44khz fix at all.

https://user-images.githubusercontent.com/7357354/199369564-608d26d5-a569-4a34-9f2e-17f911a19cde.mp4

Also, I noticed that you uploaded new screenshots, one of them is showing the 3D Map Grip menu, in there I see an extra slider that I am missing, the "Cast Range"
![image](https://user-images.githubusercontent.com/7357354/199370252-9bc1a0ea-ea5a-43a6-95ff-c4117d8c8f10.png)

**Comment by X-EcutiOnner** [comment]
I remembering... Source Code in this Repository are staying at 2018 Clients.
'Cause I just recently found it on my backing up HDD, and everything will be pushed soon.

**Comment by Singe-Horizontal** [comment]
Thank you your work is much appreciated.
